### ISSUE TITLE
Problem signing on Windows

### ISSUE THREAD

**Issue by aweaver89** [tradeparadex/starknet-signing-cpp#17]
Customer reported issues with using this code on a Windows environment. @taco-paco has been looking over this and discovered that while there were some errors that could be corrected, there seems to be an underlying compatibility issue with non-Unix environments.

**Comment by aweaver89** [comment]
@taco-paco has discovered this and the customer is currently trying to build this on WSL to see if this will work temporarily.

**Comment by filbert-nicholas** [comment]
Latest error he faced is cannot find cargo version

CMake Error at _deps/corrosion-src/cmake/FindRust.cmake:23 (message):
  Failed to get cargo version.

  /home/sherwinseah/.cargo/bin/cargo --version failed with error: `1
Call Stack (most recent call first):
  _deps/corrosion-src/cmake/FindRust.cmake:537 (_findrust_failed)
  _deps/corrosion-src/cmake/Corrosion.cmake:63 (find_package)
  _deps/corrosion-src/CMakeLists.txt:73 (include)

**Comment by taco-paco** [comment]
Closing because windows builds are supported now
