### ISSUE TITLE
Errors from OpenSSL of "undefined reference to `EVP_PKEY_id`"

### ISSUE THREAD

**Issue by aweaver89** [tradeparadex/starknet-signing-cpp#18]
A customer reached out with the following error:
![image](https://github.com/tradeparadex/starknet-signing-cpp/assets/43756933/c3839dc2-a5f6-4ee3-9ced-7b792072ce51)

This is preventing them from signing correctly.

**Comment by aweaver89** [comment]
After getting logs and investigations by @taco-paco - we've provided them the following instructions:

> specifying compiler to conan in build.sh
conan install . --build=missing -s compiler=clang -s compiler.version=11
or compiler.version=14

Wating to see if this works for them.

**Comment by taco-paco** [comment]
libcurl/7.70.0 isn't supported by ConanCenter anymore. Conan recipe didn't work properly and that's why libcurl wouldn't be able to link with product
